modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/aurilisdev/Ballistix" #optional
[[mods]] #mandatory
modId="ballistix" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ballistix" #mandatory
displayURL="https://github.com/aurilisdev/Ballistix" #optional
logoFile="ballistix.png" #optional
credits="Thanks to all contributors" #optional
authors="aurilisdev" #optional
description='''
'''
[[dependencies.ballistix]]
    modId="electrodynamics"
    mandatory=true
    versionRange="[1.1,)"
    ordering="NONE"
    side="BOTH"